-- database/supabase_schema.sql
-- Converted from MySQL to Supabase PostgreSQL syntax

-- 1. Drop existing tables if any (Cascade removes dependencies)
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS shipments CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS wishlist CASCADE;
DROP TABLE IF EXISTS cart_items CASCADE;
DROP TABLE IF EXISTS cart CASCADE;
DROP TABLE IF EXISTS addresses CASCADE;
DROP TABLE IF EXISTS product_images CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 2. Create helper function for updated_at timestamps
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 3. Create Tables

CREATE TABLE users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(15),
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) DEFAULT 'customer' CHECK (role IN ('customer', 'admin')),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_modified_column();

CREATE TABLE categories (
    category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
    product_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INT,
    product_name VARCHAR(150) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    stock_quantity INT DEFAULT 0,
    is_customizable BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) 
        REFERENCES categories(category_id) 
        ON DELETE SET NULL
);
CREATE TRIGGER update_products_updated_at BEFORE UPDATE ON products FOR EACH ROW EXECUTE FUNCTION update_modified_column();

CREATE TABLE product_images (
    image_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INT NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    display_order INT DEFAULT 0,
    is_primary BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_image_product FOREIGN KEY (product_id) 
        REFERENCES products(product_id) 
        ON DELETE CASCADE
);

CREATE TABLE addresses (
    address_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    phone VARCHAR(15) NOT NULL,
    address_line VARCHAR(255) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    pincode VARCHAR(10) NOT NULL,
    CONSTRAINT fk_address_user FOREIGN KEY (user_id) 
        REFERENCES users(user_id) 
        ON DELETE CASCADE
);

CREATE TABLE cart (
    cart_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cart_user FOREIGN KEY (user_id) 
        REFERENCES users(user_id) 
        ON DELETE CASCADE
);

CREATE TABLE cart_items (
    cart_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    custom_image_url TEXT,
    custom_text VARCHAR(255),
    custom_font VARCHAR(100),
    custom_font_size INT,
    custom_font_color VARCHAR(50),
    custom_rotation INT,
    custom_scale DECIMAL(5,2),
    custom_position_x INT,
    custom_position_y INT,
    CONSTRAINT fk_cart_item_cart FOREIGN KEY (cart_id) 
        REFERENCES cart(cart_id) 
        ON DELETE CASCADE,
    CONSTRAINT fk_cart_item_product FOREIGN KEY (product_id) 
        REFERENCES products(product_id) 
        ON DELETE CASCADE
);

CREATE TABLE wishlist (
    wishlist_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    product_id INT NOT NULL,
    CONSTRAINT fk_wishlist_user FOREIGN KEY (user_id) 
        REFERENCES users(user_id) 
        ON DELETE CASCADE,
    CONSTRAINT fk_wishlist_product FOREIGN KEY (product_id) 
        REFERENCES products(product_id) 
        ON DELETE CASCADE,
    CONSTRAINT uq_user_product_wishlist UNIQUE (user_id, product_id)
);

CREATE TABLE orders (
    order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    address_id INT NOT NULL,
    total_amount DECIMAL(10, 2) NOT NULL,
    order_status VARCHAR(20) DEFAULT 'pending' CHECK (order_status IN ('pending', 'processing', 'shipped', 'delivered', 'cancelled')),
    payment_status VARCHAR(20) DEFAULT 'pending' CHECK (payment_status IN ('pending', 'paid', 'failed', 'refunded')),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_order_user FOREIGN KEY (user_id) 
        REFERENCES users(user_id) 
        ON DELETE RESTRICT,
    CONSTRAINT fk_order_address FOREIGN KEY (address_id) 
        REFERENCES addresses(address_id) 
        ON DELETE RESTRICT
);

CREATE TABLE order_items (
    order_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    custom_image_url TEXT,
    custom_text VARCHAR(255),
    custom_font VARCHAR(100),
    custom_font_size INT,
    custom_font_color VARCHAR(50),
    custom_rotation INT,
    custom_scale DECIMAL(5,2),
    custom_position_x INT,
    custom_position_y INT,
    CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) 
        REFERENCES orders(order_id) 
        ON DELETE CASCADE,
    CONSTRAINT fk_order_item_product FOREIGN KEY (product_id) 
        REFERENCES products(product_id) 
        ON DELETE RESTRICT
);

CREATE TABLE payments (
    payment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    razorpay_payment_id VARCHAR(100) UNIQUE,
    payment_status VARCHAR(20) DEFAULT 'pending' CHECK (payment_status IN ('pending', 'completed', 'failed', 'refunded')),
    payment_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payment_order FOREIGN KEY (order_id) 
        REFERENCES orders(order_id) 
        ON DELETE CASCADE
);

CREATE TABLE shipments (
    shipment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL,
    courier_name VARCHAR(100),
    tracking_number VARCHAR(100),
    shipment_status VARCHAR(20) DEFAULT 'pending' CHECK (shipment_status IN ('pending', 'shipped', 'in_transit', 'delivered', 'returned')),
    expected_delivery DATE,
    CONSTRAINT fk_shipment_order FOREIGN KEY (order_id) 
        REFERENCES orders(order_id) 
        ON DELETE CASCADE
);

CREATE TABLE reviews (
    review_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INT NOT NULL,
    user_id INT NOT NULL,
    rating INT NOT NULL,
    review TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_review_product FOREIGN KEY (product_id) 
        REFERENCES products(product_id) 
        ON DELETE CASCADE,
    CONSTRAINT fk_review_user FOREIGN KEY (user_id) 
        REFERENCES users(user_id) 
        ON DELETE CASCADE,
    CONSTRAINT chk_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT uq_user_product_review UNIQUE (user_id, product_id)
);

-- 4. Insert Sample Data

INSERT INTO users (user_id, first_name, last_name, email, phone, password, role, is_active) VALUES
(1, 'Admin', 'User', 'admin@framewala.com', '9876543210', '$2b$10$F.ER12vPYy/xRlw9puR6ourRrV8s9vaGZVAAStz41cgZ7rwfB60WO', 'admin', TRUE),
(2, 'Raj', 'Sharma', 'raj.sharma@example.com', '9876543211', 'rajsecure456', 'customer', TRUE),
(3, 'Priya', 'Patel', 'priya.patel@example.com', '9876543212', 'priyapass789', 'customer', TRUE);

INSERT INTO categories (category_id, category_name, description) VALUES
(1, 'Photo Frames', 'Beautiful wooden, collage, and metallic photo frames to capture your memories.'),
(2, 'Printed Mugs', 'Personalized ceramic, magic, and travel mugs with your customized designs.'),
(3, 'Printed T-Shirts', 'Premium cotton t-shirts with graphic designs and custom text/photo printing.'),
(4, 'Customized Gifts', 'Engraved wooden plaques, personalized keychains, and custom cushions.');

INSERT INTO products (product_id, category_id, product_name, description, price, stock_quantity, is_customizable) VALUES
(1, 1, 'Collage Photo Frame (8x10)', 'A collage photo frame holding up to 4 photos. Perfect for family memories.', 599.00, 50, TRUE),
(2, 1, 'Classic Wooden Frame (A4)', 'Elegant matte-finished solid wood photo frame for certificates and photos.', 399.00, 100, FALSE),
(3, 2, 'Magic Photo Mug', 'Black ceramic mug that reveals your custom photo when hot liquid is poured in.', 299.00, 80, TRUE),
(4, 2, 'Classic White Mug', 'Standard 11oz white ceramic mug suitable for tea, coffee, and daily use.', 149.00, 150, FALSE),
(5, 3, 'Custom Photo T-Shirt', 'Unisex regular fit cotton t-shirt with a high-quality print of your custom image.', 499.00, 40, TRUE),
(6, 3, 'Oversized Plain Tee', 'Casual drop-shoulder pure cotton t-shirt in solid olive green.', 349.00, 120, FALSE),
(7, 4, 'Engraved Wooden Plaque', 'Maple wood plaque with custom laser-engraved photo and text.', 799.00, 30, TRUE),
(8, 4, 'Personalized Metallic Keychain', 'Durable stainless steel keychain with laser-engraved name or vehicle number.', 99.00, 200, TRUE);

INSERT INTO product_images (image_id, product_id, image_url, display_order, is_primary) VALUES
(1, 1, 'https://images.cloudinary.com/framewala/collage_frame.jpg', 1, TRUE),
(2, 1, 'https://images.cloudinary.com/framewala/collage_frame_back.jpg', 2, FALSE),
(3, 1, 'https://images.cloudinary.com/framewala/collage_frame_wall.jpg', 3, FALSE),
(4, 2, 'https://images.cloudinary.com/framewala/classic_wooden.jpg', 1, TRUE),
(5, 3, 'https://images.cloudinary.com/framewala/magic_mug.jpg', 1, TRUE),
(6, 3, 'https://images.cloudinary.com/framewala/magic_mug_empty.jpg', 2, FALSE),
(7, 3, 'https://images.cloudinary.com/framewala/magic_mug_revealed.jpg', 3, FALSE),
(8, 4, 'https://images.cloudinary.com/framewala/white_mug.jpg', 1, TRUE),
(9, 5, 'https://images.cloudinary.com/framewala/photo_tshirt.jpg', 1, TRUE),
(10, 6, 'https://images.cloudinary.com/framewala/oversized_tee.jpg', 1, TRUE),
(11, 7, 'https://images.cloudinary.com/framewala/wooden_plaque.jpg', 1, TRUE),
(12, 7, 'https://images.cloudinary.com/framewala/wooden_plaque_box.jpg', 2, FALSE),
(13, 8, 'https://images.cloudinary.com/framewala/keychain.jpg', 1, TRUE);

INSERT INTO addresses (address_id, user_id, full_name, phone, address_line, city, state, pincode) VALUES
(1, 2, 'Raj Sharma', '9876543211', 'Flat No. 402, Sunshine Heights, Sector 15', 'Mumbai', 'Maharashtra', '400011'),
(2, 2, 'Raj Sharma (Office)', '9876543211', 'TCS Building, 5th Floor, IT Park', 'Pune', 'Maharashtra', '411001'),
(3, 3, 'Priya Patel', '9876543212', 'B-104, Green Valley Apartments, Near Lake Road', 'Ahmedabad', 'Gujarat', '380015');

INSERT INTO cart (cart_id, user_id) VALUES
(1, 2),
(2, 3);

INSERT INTO cart_items (cart_item_id, cart_id, product_id, quantity) VALUES
(1, 1, 3, 2),
(2, 1, 8, 1);

INSERT INTO wishlist (wishlist_id, user_id, product_id) VALUES
(1, 3, 1),
(2, 3, 7);

INSERT INTO orders (order_id, user_id, address_id, total_amount, order_status, payment_status, created_at) VALUES
(1, 2, 1, 998.00, 'shipped', 'paid', '2026-08-01 10:30:00'),
(2, 3, 3, 799.00, 'pending', 'pending', '2026-08-02 14:15:00');

INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price) VALUES
(1, 1, 1, 1, 599.00),
(2, 1, 2, 1, 399.00),
(3, 2, 7, 1, 799.00);

INSERT INTO payments (payment_id, order_id, payment_method, razorpay_payment_id, payment_status, payment_date) VALUES
(1, 1, 'UPI', 'pay_OP12345xyz', 'completed', '2026-08-01 10:32:00');

INSERT INTO shipments (shipment_id, order_id, courier_name, tracking_number, shipment_status, expected_delivery) VALUES
(1, 1, 'Delhivery', 'DEL874620194', 'shipped', '2026-08-05');

INSERT INTO reviews (review_id, product_id, user_id, rating, review) VALUES
(1, 1, 2, 5, 'Superb build quality! The customizable design made a wonderful birthday gift for my parents.');

-- 5. Reset sequences for identity columns after manual ID insertion
SELECT setval(pg_get_serial_sequence('users', 'user_id'), coalesce(max(user_id), 1), max(user_id) IS NOT null) FROM users;
SELECT setval(pg_get_serial_sequence('categories', 'category_id'), coalesce(max(category_id), 1), max(category_id) IS NOT null) FROM categories;
SELECT setval(pg_get_serial_sequence('products', 'product_id'), coalesce(max(product_id), 1), max(product_id) IS NOT null) FROM products;
SELECT setval(pg_get_serial_sequence('product_images', 'image_id'), coalesce(max(image_id), 1), max(image_id) IS NOT null) FROM product_images;
SELECT setval(pg_get_serial_sequence('addresses', 'address_id'), coalesce(max(address_id), 1), max(address_id) IS NOT null) FROM addresses;
SELECT setval(pg_get_serial_sequence('cart', 'cart_id'), coalesce(max(cart_id), 1), max(cart_id) IS NOT null) FROM cart;
SELECT setval(pg_get_serial_sequence('cart_items', 'cart_item_id'), coalesce(max(cart_item_id), 1), max(cart_item_id) IS NOT null) FROM cart_items;
SELECT setval(pg_get_serial_sequence('wishlist', 'wishlist_id'), coalesce(max(wishlist_id), 1), max(wishlist_id) IS NOT null) FROM wishlist;
SELECT setval(pg_get_serial_sequence('orders', 'order_id'), coalesce(max(order_id), 1), max(order_id) IS NOT null) FROM orders;
SELECT setval(pg_get_serial_sequence('order_items', 'order_item_id'), coalesce(max(order_item_id), 1), max(order_item_id) IS NOT null) FROM order_items;
SELECT setval(pg_get_serial_sequence('payments', 'payment_id'), coalesce(max(payment_id), 1), max(payment_id) IS NOT null) FROM payments;
SELECT setval(pg_get_serial_sequence('shipments', 'shipment_id'), coalesce(max(shipment_id), 1), max(shipment_id) IS NOT null) FROM shipments;
SELECT setval(pg_get_serial_sequence('reviews', 'review_id'), coalesce(max(review_id), 1), max(review_id) IS NOT null) FROM reviews;
